---
title: "Image Anlysis"
author: "Xuehan Liu (xl2615)"
date: "4/21/2017"
output: pdf_document
---

###Load libraries
```{r}
library(EBImage)
#install.packages("jpeg")
library(jpeg)
library(OpenImageR)
```


###Extract HoG Features from images

```{r}
setwd("/Users/xuehan/Desktop/Spr2017-proj5-grp8/doc")
source("../lib/HOGFeature.R")
experiment_dir <- "../data/"
img_dir <- paste(experiment_dir, "Images_full/", sep="")
h<-hogfeature(img_dir,export=T)
h<-data.frame(h)
h$id<-file.names
write.csv(h,file="HoG.csv")
#HoG.csv is under the doc 

```

###Extract RGB Features from images 
```{r}
file_paths <- paste(img_dir, 1, sep = "/")
img <- readImage("/Users/xuehan/Desktop/Spr2017-proj5-grp8/data/Images_full/american-art-n09633_1.jpg")
imageData(img)


feature <- function(img_dir) {
  
  ### Constructs features out of images for training/testing
  
  ### img_dir: class "character", path to directory of images to be processed
  
  ##### CURRENT STATUS (2016/03/18 19:30): 
  ##### This function constructs only grayscale features.
  
  n_files <- length(list.files(img_dir))
  file_names <- list.files(img_dir, pattern = "[[:digit:]].jpg")
  #file_names <- sort(file_names)
  file_paths <- rep(NA_character_, length(file_names))
  for (i in 1:length(file_names)) {
    file_paths[i] <- paste(img_dir, file_names[i], sep = "/")
  }
  #file_paths <- sort(file_paths)
  
  rgb_feature <- matrix(NA, nrow = 256, ncol = n_files)

  #       constructed for those images
  for (i in 1:n_files) {
    tryCatch({
      img_rgb <- readImage(file_paths[i])
      mat <- imageData(img_rgb)
      n <- 256
      nBin <- seq(0, 1, length.out = n)
      freq_rgb <- as.data.frame(table(factor(findInterval(mat, nBin), levels = 1:n)))
      rgb_feature[,i] <- as.numeric(freq_gray$Freq)/(ncol(mat)*nrow(mat))
    }, 
    error = function(c) "invalid or corrupt JPEG file")
  }
  return(rgb_feature)
}

rgb<-feature(img_dir)

```


###Extract RGB Features from images 

```{r}
#setwd("/Users/xuehan/Desktop/Spr2017-proj5-grp8")
source("/Users/xuehan/Desktop/Spr2017-proj5-grp8/lib/RGBfeature.R")
dir <- "/Users/xuehan/Desktop/Spr2017-proj5-grp8/data/"
experiment_dir3 <- "/Users/xuehan/Desktop/Spr2017-proj5-grp8/data/Images"
img_dir2 <- paste(experiment_dir3, "Images_full", sep="")

#file.rename(from=list.files(experiment_dir3,pattern="american-art-n09633_*.jpg",to=paste0(experiment_dir3,"american-art-n09633_", 1:143,"jpg")))

rgb<-rgbfeature(img_dir2,file.names)

#rgb<-rgbfeature(img_dir2,"master-paintings-19th-century-european-n09600")



img_dir_full <- paste(dir, "Images_full", sep="")

n.files<-length(list.files(img_dir_full))
n.files

file.names <- list.files(img_dir_full,pattern="*.jpg") 
file.names

new.names<-paste("image",1:n.files,".jpg")

file.rename(from=file.names,to=new.names)


```


